version: '3.9'

services:
  node:
    build:
      context: .
    restart: always
    ports:
      - 3001:3000
    volumes:
      - ./:/app
    networks:
      - system
    command: pnpm dev

networks:
  system:
